name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: 10.0.x
  BICEP_VERSION: 0.42.1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Use .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Use Bicep ${{ env.BICEP_VERSION }}
      run: |
        az config set bicep.use_binary_from_path=false
        az bicep install --version v${{ env.BICEP_VERSION }}

    - name: Build project
      run: dotnet build -c Release ./src

    - name: Lint C# code
      run: dotnet format --verify-no-changes --verbosity detailed --no-restore ./src

    - name: Lint Bicep template
      run: az bicep build -f ./deploy/azuredeploy.bicep && git diff --exit-code --quiet
